name: Testing CI (Bruno Ro7) - Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v3
    # Setup do Job
    - name: Instala as Dependências
    - run: npm install
    -name: Run teste do Eslint
    - run: eslint . --ext .js, .jsx, .ts, .tsx

    # Run teste do Eslint
      # uses: actions/setup-node@v3
    # - run: npm run lint
      # with:
          # github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          # extensions: 'js,jsx,ts,tsx'
          # annotations: true
          # issueSummaryType: full
          # reportIgnoredFiles: true