name: Testing CI (Bruno Ro7) - Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Projeto
    - uses: actions/checkout@v3
      # uses: actions/setup-node@v3

    # Setup do Job
    - name: Instala as Dependências
    - run: npm install
    - run: |
        npm install eslint

    # Run teste do Eslint
    - run: npm run lint
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          issueSummaryType: full
          reportIgnoredFiles: true