name: Testing CI (Bruno Ro7) - Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout do Projeto
      uses: actions/checkout@v3

    - name: Instala Node.js
      uses: actions/setup-node@v3

    - name: Instalação das Libs
      run: npm install

    - name: Roda o EsLint
      run: npm run lint





# eslint . --ext .js, .jsx, .ts, .tsx
  # Setup do Job
    # Run teste do Eslint
      # uses: actions/setup-node@v3
    # - run: npm run lint
      # with:
          # github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          # extensions: 'js,jsx,ts,tsx'
          # annotations: true
          # issueSummaryType: full
          # reportIgnoredFiles: true